//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public protocol AppStoreConnectBaseModel: Codable, Equatable {}

extension AppStoreConnectBaseModel {
  func encode() -> [String: Any] {
    guard
      let jsonData = try? JSONEncoder().encode(self),
      let jsonValue = try? JSONSerialization.jsonObject(with: jsonData),
      let jsonDictionary = jsonValue as? [String: Any]
    else {
      return [:]
    }
    return jsonDictionary
  }
}
