//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ASCAppMediaAssetState: AppStoreConnectBaseModel {

  public enum ASCState: String, Codable, Equatable, CaseIterable {
    case awaitingUpload = "AWAITING_UPLOAD"
    case uploadComplete = "UPLOAD_COMPLETE"
    case complete = "COMPLETE"
    case failed = "FAILED"
  }

  public var errors: [ASCAppMediaStateError]?

  public var state: ASCState?

  public var warnings: [ASCAppMediaStateError]?

  public init(
    errors: [ASCAppMediaStateError]? = nil, state: ASCState? = nil,
    warnings: [ASCAppMediaStateError]? = nil
  ) {
    self.errors = errors
    self.state = state
    self.warnings = warnings
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: StringCodingKey.self)

    errors = try container.decodeArrayIfPresent("errors")
    state = try container.decodeIfPresent("state")
    warnings = try container.decodeArrayIfPresent("warnings")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: StringCodingKey.self)

    try container.encodeIfPresent(errors, forKey: "errors")
    try container.encodeIfPresent(state, forKey: "state")
    try container.encodeIfPresent(warnings, forKey: "warnings")
  }

}
