//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ASCBetaAppReviewDetail: AppStoreConnectBaseModel {

  public enum ASCType: String, Codable, Equatable, CaseIterable {
    case betaAppReviewDetails = "betaAppReviewDetails"
  }

  public var links: ASCResourceLinks

  public var id: String

  public var type: ASCType

  public var attributes: Attributes?

  public var relationships: Relationships?

  public struct Attributes: AppStoreConnectBaseModel {

    public var contactEmail: String?

    public var contactFirstName: String?

    public var contactLastName: String?

    public var contactPhone: String?

    public var demoAccountName: String?

    public var demoAccountPassword: String?

    public var demoAccountRequired: Bool?

    public var notes: String?

    public init(
      contactEmail: String? = nil, contactFirstName: String? = nil, contactLastName: String? = nil,
      contactPhone: String? = nil, demoAccountName: String? = nil,
      demoAccountPassword: String? = nil, demoAccountRequired: Bool? = nil, notes: String? = nil
    ) {
      self.contactEmail = contactEmail
      self.contactFirstName = contactFirstName
      self.contactLastName = contactLastName
      self.contactPhone = contactPhone
      self.demoAccountName = demoAccountName
      self.demoAccountPassword = demoAccountPassword
      self.demoAccountRequired = demoAccountRequired
      self.notes = notes
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: StringCodingKey.self)

      contactEmail = try container.decodeIfPresent("contactEmail")
      contactFirstName = try container.decodeIfPresent("contactFirstName")
      contactLastName = try container.decodeIfPresent("contactLastName")
      contactPhone = try container.decodeIfPresent("contactPhone")
      demoAccountName = try container.decodeIfPresent("demoAccountName")
      demoAccountPassword = try container.decodeIfPresent("demoAccountPassword")
      demoAccountRequired = try container.decodeIfPresent("demoAccountRequired")
      notes = try container.decodeIfPresent("notes")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: StringCodingKey.self)

      try container.encodeIfPresent(contactEmail, forKey: "contactEmail")
      try container.encodeIfPresent(contactFirstName, forKey: "contactFirstName")
      try container.encodeIfPresent(contactLastName, forKey: "contactLastName")
      try container.encodeIfPresent(contactPhone, forKey: "contactPhone")
      try container.encodeIfPresent(demoAccountName, forKey: "demoAccountName")
      try container.encodeIfPresent(demoAccountPassword, forKey: "demoAccountPassword")
      try container.encodeIfPresent(demoAccountRequired, forKey: "demoAccountRequired")
      try container.encodeIfPresent(notes, forKey: "notes")
    }

  }

  public struct Relationships: AppStoreConnectBaseModel {

    public var app: App?

    public struct App: AppStoreConnectBaseModel {

      public var data: DataType?

      public var links: Links?

      public struct DataType: AppStoreConnectBaseModel {

        public enum ASCType: String, Codable, Equatable, CaseIterable {
          case apps = "apps"
        }

        public var id: String

        public var type: ASCType

        public init(id: String, type: ASCType) {
          self.id = id
          self.type = type
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: StringCodingKey.self)

          id = try container.decode("id")
          type = try container.decode("type")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: StringCodingKey.self)

          try container.encode(id, forKey: "id")
          try container.encode(type, forKey: "type")
        }

      }

      public struct Links: AppStoreConnectBaseModel {

        public var related: String?

        public var `self`: String?

        public init(related: String? = nil, `self`: String? = nil) {
          self.related = related
          self.`self` = `self`
        }

        public init(from decoder: Decoder) throws {
          let container = try decoder.container(keyedBy: StringCodingKey.self)

          related = try container.decodeIfPresent("related")
          `self` = try container.decodeIfPresent("self")
        }

        public func encode(to encoder: Encoder) throws {
          var container = encoder.container(keyedBy: StringCodingKey.self)

          try container.encodeIfPresent(related, forKey: "related")
          try container.encodeIfPresent(`self`, forKey: "self")
        }

      }

      public init(data: DataType? = nil, links: Links? = nil) {
        self.data = data
        self.links = links
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        data = try container.decodeIfPresent("data")
        links = try container.decodeIfPresent("links")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(data, forKey: "data")
        try container.encodeIfPresent(links, forKey: "links")
      }

    }

    public init(app: App? = nil) {
      self.app = app
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: StringCodingKey.self)

      app = try container.decodeIfPresent("app")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: StringCodingKey.self)

      try container.encodeIfPresent(app, forKey: "app")
    }

  }

  public init(
    links: ASCResourceLinks, id: String, type: ASCType, attributes: Attributes? = nil,
    relationships: Relationships? = nil
  ) {
    self.links = links
    self.id = id
    self.type = type
    self.attributes = attributes
    self.relationships = relationships
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: StringCodingKey.self)

    links = try container.decode("links")
    id = try container.decode("id")
    type = try container.decode("type")
    attributes = try container.decodeIfPresent("attributes")
    relationships = try container.decodeIfPresent("relationships")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: StringCodingKey.self)

    try container.encode(links, forKey: "links")
    try container.encode(id, forKey: "id")
    try container.encode(type, forKey: "type")
    try container.encodeIfPresent(attributes, forKey: "attributes")
    try container.encodeIfPresent(relationships, forKey: "relationships")
  }

}
