//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ASCBundleIdCapabilityResponse: AppStoreConnectBaseModel {

  public var data: ASCBundleIdCapability

  public var links: ASCDocumentLinks

  public init(data: ASCBundleIdCapability, links: ASCDocumentLinks) {
    self.data = data
    self.links = links
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: StringCodingKey.self)

    data = try container.decode("data")
    links = try container.decode("links")
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: StringCodingKey.self)

    try container.encode(data, forKey: "data")
    try container.encode(links, forKey: "links")
  }

}
