//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public struct ASCCapabilityOption: AppStoreConnectBaseModel {

    public enum ASCKey: String, Codable, Equatable, CaseIterable {
        case xcode5 = "XCODE_5"
        case xcode6 = "XCODE_6"
        case completeProtection = "COMPLETE_PROTECTION"
        case protectedUnlessOpen = "PROTECTED_UNLESS_OPEN"
        case protectedUntilFirstUserAuth = "PROTECTED_UNTIL_FIRST_USER_AUTH"
        case primaryAppConsent = "PRIMARY_APP_CONSENT"
    }

    public var description: String?

    public var enabled: Bool?

    public var enabledByDefault: Bool?

    public var key: ASCKey?

    public var name: String?

    public var supportsWildcard: Bool?

    public init(description: String? = nil, enabled: Bool? = nil, enabledByDefault: Bool? = nil, key: ASCKey? = nil, name: String? = nil, supportsWildcard: Bool? = nil) {
        self.description = description
        self.enabled = enabled
        self.enabledByDefault = enabledByDefault
        self.key = key
        self.name = name
        self.supportsWildcard = supportsWildcard
    }

    public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: StringCodingKey.self)

        description = try container.decodeIfPresent("description")
        enabled = try container.decodeIfPresent("enabled")
        enabledByDefault = try container.decodeIfPresent("enabledByDefault")
        key = try container.decodeIfPresent("key")
        name = try container.decodeIfPresent("name")
        supportsWildcard = try container.decodeIfPresent("supportsWildcard")
    }

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: StringCodingKey.self)

        try container.encodeIfPresent(description, forKey: "description")
        try container.encodeIfPresent(enabled, forKey: "enabled")
        try container.encodeIfPresent(enabledByDefault, forKey: "enabledByDefault")
        try container.encodeIfPresent(key, forKey: "key")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(supportsWildcard, forKey: "supportsWildcard")
    }

}
