//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation

public enum ASCKidsAgeBand: String, Codable, Equatable, CaseIterable {
  case fiveAndUnder = "FIVE_AND_UNDER"
  case sixToEight = "SIX_TO_EIGHT"
  case nineToEleven = "NINE_TO_ELEVEN"
}
