//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

import Foundation
#if canImport(AppStoreConnectModels)
import AppStoreConnectModels
import AppStoreConnectSharedCode
#endif

extension AppStoreConnect.BundleIds {

    public enum BundleIdsGetCollection {

        public static let service = APIService<Response>(id: "bundleIds-get_collection", tag: "BundleIds", method: "GET", path: "/v1/bundleIds", hasBody: false, securityRequirement: SecurityRequirement(type: "itc-bearer-token", scopes: []))

        /** filter by attribute 'platform' */
        public enum ASCFilterplatform: String, Codable, Equatable, CaseIterable {
            case ios = "IOS"
            case macOs = "MAC_OS"
        }

        /** comma-separated list of sort expressions; resources will be sorted as specified */
        public enum ASCSort: String, Codable, Equatable, CaseIterable {
            case id = "id"
            case id = "-id"
            case identifier = "identifier"
            case identifier = "-identifier"
            case name = "name"
            case name = "-name"
            case platform = "platform"
            case platform = "-platform"
            case seedId = "seedId"
            case seedId = "-seedId"
        }

        /** the fields to include for returned resources of type bundleIds */
        public enum ASCFieldsbundleIds: String, Codable, Equatable, CaseIterable {
            case app = "app"
            case bundleIdCapabilities = "bundleIdCapabilities"
            case identifier = "identifier"
            case name = "name"
            case platform = "platform"
            case profiles = "profiles"
            case seedId = "seedId"
        }

        /** comma-separated list of relationships to include */
        public enum ASCInclude: String, Codable, Equatable, CaseIterable {
            case app = "app"
            case bundleIdCapabilities = "bundleIdCapabilities"
            case profiles = "profiles"
        }

        /** the fields to include for returned resources of type bundleIdCapabilities */
        public enum ASCFieldsbundleIdCapabilities: String, Codable, Equatable, CaseIterable {
            case bundleId = "bundleId"
            case capabilityType = "capabilityType"
            case settings = "settings"
        }

        /** the fields to include for returned resources of type profiles */
        public enum ASCFieldsprofiles: String, Codable, Equatable, CaseIterable {
            case bundleId = "bundleId"
            case certificates = "certificates"
            case createdDate = "createdDate"
            case devices = "devices"
            case expirationDate = "expirationDate"
            case name = "name"
            case platform = "platform"
            case profileContent = "profileContent"
            case profileState = "profileState"
            case profileType = "profileType"
            case uuid = "uuid"
        }

        /** the fields to include for returned resources of type apps */
        public enum ASCFieldsapps: String, Codable, Equatable, CaseIterable {
            case appInfos = "appInfos"
            case appStoreVersions = "appStoreVersions"
            case availableInNewTerritories = "availableInNewTerritories"
            case availableTerritories = "availableTerritories"
            case betaAppLocalizations = "betaAppLocalizations"
            case betaAppReviewDetail = "betaAppReviewDetail"
            case betaGroups = "betaGroups"
            case betaLicenseAgreement = "betaLicenseAgreement"
            case betaTesters = "betaTesters"
            case builds = "builds"
            case bundleId = "bundleId"
            case contentRightsDeclaration = "contentRightsDeclaration"
            case endUserLicenseAgreement = "endUserLicenseAgreement"
            case gameCenterEnabledVersions = "gameCenterEnabledVersions"
            case inAppPurchases = "inAppPurchases"
            case isOrEverWasMadeForKids = "isOrEverWasMadeForKids"
            case name = "name"
            case perfPowerMetrics = "perfPowerMetrics"
            case preOrder = "preOrder"
            case preReleaseVersions = "preReleaseVersions"
            case prices = "prices"
            case primaryLocale = "primaryLocale"
            case sku = "sku"
        }

        public final class Request: APIRequest<Response> {

            public struct Options {

                /** filter by attribute 'identifier' */
                public var filteridentifier: [String]?

                /** filter by attribute 'name' */
                public var filtername: [String]?

                /** filter by attribute 'platform' */
                public var filterplatform: [ASCFilterplatform]?

                /** filter by attribute 'seedId' */
                public var filterseedId: [String]?

                /** filter by id(s) */
                public var filterid: [String]?

                /** comma-separated list of sort expressions; resources will be sorted as specified */
                public var sort: [ASCSort]?

                /** the fields to include for returned resources of type bundleIds */
                public var fieldsbundleIds: [ASCFieldsbundleIds]?

                /** maximum resources per page */
                public var limit: Int?

                /** comma-separated list of relationships to include */
                public var include: [ASCInclude]?

                /** the fields to include for returned resources of type bundleIdCapabilities */
                public var fieldsbundleIdCapabilities: [ASCFieldsbundleIdCapabilities]?

                /** the fields to include for returned resources of type profiles */
                public var fieldsprofiles: [ASCFieldsprofiles]?

                /** the fields to include for returned resources of type apps */
                public var fieldsapps: [ASCFieldsapps]?

                /** maximum number of related bundleIdCapabilities returned (when they are included) */
                public var limitbundleIdCapabilities: Int?

                /** maximum number of related profiles returned (when they are included) */
                public var limitprofiles: Int?

                public init(filteridentifier: [String]? = nil, filtername: [String]? = nil, filterplatform: [ASCFilterplatform]? = nil, filterseedId: [String]? = nil, filterid: [String]? = nil, sort: [ASCSort]? = nil, fieldsbundleIds: [ASCFieldsbundleIds]? = nil, limit: Int? = nil, include: [ASCInclude]? = nil, fieldsbundleIdCapabilities: [ASCFieldsbundleIdCapabilities]? = nil, fieldsprofiles: [ASCFieldsprofiles]? = nil, fieldsapps: [ASCFieldsapps]? = nil, limitbundleIdCapabilities: Int? = nil, limitprofiles: Int? = nil) {
                    self.filteridentifier = filteridentifier
                    self.filtername = filtername
                    self.filterplatform = filterplatform
                    self.filterseedId = filterseedId
                    self.filterid = filterid
                    self.sort = sort
                    self.fieldsbundleIds = fieldsbundleIds
                    self.limit = limit
                    self.include = include
                    self.fieldsbundleIdCapabilities = fieldsbundleIdCapabilities
                    self.fieldsprofiles = fieldsprofiles
                    self.fieldsapps = fieldsapps
                    self.limitbundleIdCapabilities = limitbundleIdCapabilities
                    self.limitprofiles = limitprofiles
                }
            }

            public var options: Options

            public init(options: Options) {
                self.options = options
                super.init(service: BundleIdsGetCollection.service)
            }

            /// convenience initialiser so an Option doesn't have to be created
            public convenience init(filteridentifier: [String]? = nil, filtername: [String]? = nil, filterplatform: [ASCFilterplatform]? = nil, filterseedId: [String]? = nil, filterid: [String]? = nil, sort: [ASCSort]? = nil, fieldsbundleIds: [ASCFieldsbundleIds]? = nil, limit: Int? = nil, include: [ASCInclude]? = nil, fieldsbundleIdCapabilities: [ASCFieldsbundleIdCapabilities]? = nil, fieldsprofiles: [ASCFieldsprofiles]? = nil, fieldsapps: [ASCFieldsapps]? = nil, limitbundleIdCapabilities: Int? = nil, limitprofiles: Int? = nil) {
                let options = Options(filteridentifier: filteridentifier, filtername: filtername, filterplatform: filterplatform, filterseedId: filterseedId, filterid: filterid, sort: sort, fieldsbundleIds: fieldsbundleIds, limit: limit, include: include, fieldsbundleIdCapabilities: fieldsbundleIdCapabilities, fieldsprofiles: fieldsprofiles, fieldsapps: fieldsapps, limitbundleIdCapabilities: limitbundleIdCapabilities, limitprofiles: limitprofiles)
                self.init(options: options)
            }

            public override var queryParameters: [String: Any] {
                var params: [String: Any] = [:]
                if let filteridentifier = options.filteridentifier?.joined(separator: ",") {
                  params["filter[identifier]"] = filteridentifier
                }
                if let filtername = options.filtername?.joined(separator: ",") {
                  params["filter[name]"] = filtername
                }
                if let filterplatform = options.filterplatform?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["filter[platform]"] = filterplatform
                }
                if let filterseedId = options.filterseedId?.joined(separator: ",") {
                  params["filter[seedId]"] = filterseedId
                }
                if let filterid = options.filterid?.joined(separator: ",") {
                  params["filter[id]"] = filterid
                }
                if let sort = options.sort?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["sort"] = sort
                }
                if let fieldsbundleIds = options.fieldsbundleIds?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["fields[bundleIds]"] = fieldsbundleIds
                }
                if let limit = options.limit {
                  params["limit"] = limit
                }
                if let include = options.include?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["include"] = include
                }
                if let fieldsbundleIdCapabilities = options.fieldsbundleIdCapabilities?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["fields[bundleIdCapabilities]"] = fieldsbundleIdCapabilities
                }
                if let fieldsprofiles = options.fieldsprofiles?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["fields[profiles]"] = fieldsprofiles
                }
                if let fieldsapps = options.fieldsapps?.encode().map({ String(describing: $0) }).joined(separator: ",") {
                  params["fields[apps]"] = fieldsapps
                }
                if let limitbundleIdCapabilities = options.limitbundleIdCapabilities {
                  params["limit[bundleIdCapabilities]"] = limitbundleIdCapabilities
                }
                if let limitprofiles = options.limitprofiles {
                  params["limit[profiles]"] = limitprofiles
                }
                return params
            }
        }

        public enum Response: APIResponseValue, CustomStringConvertible, CustomDebugStringConvertible {
            public typealias SuccessType = ASCBundleIdsResponse

            /** List of BundleIds */
            case status200(ASCBundleIdsResponse)

            /** Parameter error(s) */
            case status400(ASCErrorResponse)

            /** Forbidden error */
            case status403(ASCErrorResponse)

            public var success: ASCBundleIdsResponse? {
                switch self {
                case .status200(let response): return response
                default: return nil
                }
            }

            public var failure: ASCErrorResponse? {
                switch self {
                case .status400(let response): return response
                case .status403(let response): return response
                default: return nil
                }
            }

            /// either success or failure value. Success is anything in the 200..<300 status code range
            public var responseResult: APIResponseResult<ASCBundleIdsResponse, ASCErrorResponse> {
                if let successValue = success {
                    return .success(successValue)
                } else if let failureValue = failure {
                    return .failure(failureValue)
                } else {
                    fatalError("Response does not have success or failure response")
                }
            }

            public var response: Any {
                switch self {
                case .status200(let response): return response
                case .status400(let response): return response
                case .status403(let response): return response
                }
            }

            public var statusCode: Int {
                switch self {
                case .status200: return 200
                case .status400: return 400
                case .status403: return 403
                }
            }

            public var successful: Bool {
                switch self {
                case .status200: return true
                case .status400: return false
                case .status403: return false
                }
            }

            public init(statusCode: Int, data: Data, decoder: ResponseDecoder) throws {
                switch statusCode {
                case 200: self = try .status200(decoder.decode(ASCBundleIdsResponse.self, from: data))
                case 400: self = try .status400(decoder.decode(ASCErrorResponse.self, from: data))
                case 403: self = try .status403(decoder.decode(ASCErrorResponse.self, from: data))
                default: throw APIClientError.unexpectedStatusCode(statusCode: statusCode, data: data)
                }
            }

            public var description: String {
                return "\(statusCode) \(successful ? "success" : "failure")"
            }

            public var debugDescription: String {
                var string = description
                let responseString = "\(response)"
                if responseString != "()" {
                    string += "\n\(responseString)"
                }
                return string
            }
        }
    }
}
