//
// Generated by SwagGen
// https://github.com/yonaskolb/SwagGen
//

extension Never: Codable {
  public init(from decoder: Decoder) throws {
    fatalError("This should never happen")
  }

  public func encode(to encoder: Encoder) throws {
    fatalError("This should never happen")
  }
}
